### ISSUE TITLE
unable to remove line entry box

### ISSUE THREAD

**Issue by davidcthomas** [irssiconnectbot/irssiconnectbot#13]
I like the line entry box introduced because of issue #2 (https://github.com/irssiconnectbot/irssiconnectbot/pull/2), however once on screen I can't seem to make it go away.  The only way to remove it I've found is to disconnect the session.  This is really obnoxious as the box covers some of the terminal and I'm not able to hit enter on the prompt.

Am I missing something?
Thanks.

**Comment by adamwg** [comment]
The only way to get rid of the line entry is to press "Done" on the keyboard.  This will insert the text that's in the box, but if it's empty this does nothing.  It is a bit inconvenient, especially if you don't have the keyboard showing.

I worked a bit on figuring out how to get the box to go away when the back button is pressed, but didn't come up with a way to do it.  I'll try to find some time to work on this again, but if anyone else can figure it out in the meantime, that would be great.

**Comment by davidcthomas** [comment]
That works great. I feel like a goob for not figuring that out myself.  

## Thanks

DavidT
