### ISSUE TITLE
[PATCH] Fix exception if character picker window items are selected via hardware keyboard

### ISSUE THREAD

**Issue by mmatuska** [irssiconnectbot/irssiconnectbot#20]
When items in the character picker dialog are selected using a hardware keyboard (arrows, enter) the application exits with an exception.

A override of the onItemClick() method is missing.

Here is the patch to fix this problem:
https://github.com/mmatuska/irssiconnectbot/commit/0e5d7207faf259347950c68326a7d4f5546d8397

**Comment by woltage** [comment]
Hi!

Thanks for patch. Can you make Pull Request? Then I can automatic merge it.

Thank you.
