### ISSUE TITLE
Program title cann't be removed in fullscreen mode on Android 4.0.x

### ISSUE THREAD

**Issue by backbone** [irssiconnectbot/irssiconnectbot#26]
Using fullscreen mode or not the program title are showing always. I've installed original ConnectBot (ssh-agent-patch), ConnectBot-pslib, VX ConnectBot but only ConnectBot-pslib works in fullscreen mode correctly.
I would like to use Irssi Connectbot fork because it force screen size. Tested device is Nexus S.

**Comment by lizsugar** [comment]
I just added a change that gives the option to remove the Action Bar on devices that display it. Are you able to download and compile this repo to check that out?

**Comment by backbone** [comment]
Thoughts move in space, just remembered about it. :)
I need some time (about 2-3 hours) to install the sdk, because I had never compiled a project under Android.

**Comment by backbone** [comment]
I confirm, the option works on Nexus S with Android-4.0.3 fine! :)
