### ISSUE TITLE
Trackball longpress on HTC Desire 2.3.3

### ISSUE THREAD

**Issue by Racle** [irssiconnectbot/irssiconnectbot#3]
What steps will reproduce the problem?
1. Longpress trackpad

What is the expected output? What do you see instead?
expected: >
What i see: blinking >

What version of the product are you using?
Newest on market

Please provide any additional information below.
Using custom rom, dhd based, http://tinyurl.com/InsertCoinN

logcat dumb: http://dl.dropbox.com/u/3556104/tt/icb_log.txt

**Comment by woltage** [comment]
Logpress trackpad? Hit that trackpad twice.

Here is "tutorial" howto use trackpad:
http://code.google.com/p/connectbot/wiki/UsageWithSoftKeyboard
