### ISSUE TITLE
To have horizontal view

### ISSUE THREAD

**Issue by matinrepo** [irssiconnectbot/irssiconnectbot#30]
I am using the application in Samsung Galaxy Tab 8.9.
It is very difficult to type as the device is vertical.
It is a lot easier when it is horizontal.

I propose the horizontal view to the application.

**Comment by lizsugar** [comment]
Do you mean putting the application in landscape mode?  It supports that already.  Go into the application settings and check what your _Rotation mode_ option is set to.  You can force it to landscape or let it rely on your rotation sensor.

**Comment by matinrepo** [comment]
That is not that easy. How can you go to the application settings of the given application in Samsung galaxy tab 8.9? - The navigation is different than in my HTC smartphone where it is easy. - The upper right logo does not have the menu item settings.

**Comment by woltage** [comment]
There is menubar @ Footer.

Working on Samsung Galaxy Tab 10.1"

**Comment by matinrepo** [comment]
@iiuusit Yes, there is the menubar but I cannot find any settings -button there. There are the symbols: [<- house two-windows screenshot arrow-up Irssi-connectbot-logo]. And the logo does not have any settings although pressed long time.

So I can find no settings to allow horizontal navigation at the footer.

**Comment by woltage** [comment]
@matinrepo .. Intresting.. You are at hostslist? Can you take screenshot from hostslist and link it here?

**Comment by matinrepo** [comment]
Here http://tinypic.com/view.php?pic=iz6e6c&s=5

**Comment by woltage** [comment]
that's not from hostslist...

Are you sure you are in correct view?

**Comment by matinrepo** [comment]
Lol, works now. Selected "automatic" to the given selection at the far right corner > Settings, in the Hostlists - view. Thank you!

**Comment by woltage** [comment]
@matinrepo No problem. Glad I could help!
