### ISSUE TITLE
TAB on search key

### ISSUE THREAD

**Issue by MoeMorox** [irssiconnectbot/irssiconnectbot#35]
Hello,

I want to use the TAB key on my search key.

I edited the urlscan = menu.add(R.string.console_menu_urlscan); in ConsoleActitvity.java like this:

public boolean onMenuItemClick(MenuItem item) {
                final TerminalView terminal = (TerminalView) findCurrentView(R.id.console_flip);

```
            /*TerminalKeyListener handler = terminal.bridge.getKeyHandler();
            handler.urlScan(terminal);*/

            ((vt320) terminal.bridge.buffer).write(0x09);
            terminal.bridge.tryKeyVibrate();

            return true;
        }
```

But it only sends [^ to the console.

Thanks for your help,

moro

**Comment by woltage** [comment]
New release closes this one.
