### ISSUE TITLE
Wrong keycodes with Asus eee pad transformer's keyboard dock

### ISSUE THREAD

**Issue by gkatsev** [irssiconnectbot/irssiconnectbot#6]
I just got an eeepad transformer and when I run irssi-connectbot with the Asus eee pad transformer's keyboard dock.
For example, when I press the alt-key, I get a `/'. Ctrl is ignore. And characters like ( which are entered on the keyboard via shift-9.

Also, I noticed similar behaviour with the Hacker's Keyboard android keyboard.

**Comment by gkatsev** [comment]
So, swithing to another non-asus softkeyboard, and then disconnecting and reconnecting the hardware keyboard fixes the problems that are happening with the keys that are hidden behind the numbers and shift key, i.e. (.
Alt no longer produced a '/' but ctrl and alt still don't work as ctrl and meta.

**Comment by legoman666** [comment]
I'm having the same issue on my Asus Transformer. The software touch keyboards work fine, the issue only exists with the hardware dock.

**Comment by unexist** [comment]
I can confirm the issues, the return key sends a space on my Xoom with a BT keyboard. Doesn't happen in other apps like Better Terminal Emulator. I am not actually sure how the stuff derives from connectbot so I probably report it there, too.

Update: There is a pending ticket for the problems with the Xoom: http://code.google.com/p/connectbot/issues/detail?id=434

**Comment by gkatsev** [comment]
Supposedly fixed with issue #32
