### ISSUE TITLE
Actionbar in 1.7.1-irssi 

### ISSUE THREAD

**Issue by unexist** [irssiconnectbot/irssiconnectbot#9]
Why is there an actionbar in the latest version on HC? The previous option menu was fine and didn't decrease the available screen size. Due to the softkeyboard it is quite limited even on large sceeens.

I know it is FOSS, but I'd rather ask if it is possible to add an option to disable the actionbar?

**Comment by woltage** [comment]
Can you share some kind of screenshot? Didn't catch the problem from this message...

Option menu doesn't decrease screen size @ My Galaxy Tab 10.1.

**Comment by unexist** [comment]
Uhm I reverted to the previous version, but generally I am speaking about the actionbar at the top of the screen. It just contains the logo and the option button with stuff like 'Disconnect' for the current connection.

If this doesn't clarify the issue I will add a screenshot later.

**Comment by unexist** [comment]
Meh, stupid UI. Sorry, wrong button. ;)

**Comment by woltage** [comment]
Yeah, add screenshot and more information about your device.

Thanks.

**Comment by unexist** [comment]
Sorry for the delay, was a bit lazy to update and then downgrade for both shots. Should be pretty self-explanatory.

http://i.imgur.com/xtwjW.png

(Moto Xoom/HC 3.1)

**Comment by unexist** [comment]
I don't see any commits that fix that, so why did you close it?

**Comment by woltage** [comment]
My bad... Wrong button :D

**Comment by woltage** [comment]
In new release.

**Comment by unexist** [comment]
When exactly can I expect that new release? Tired of updating and then to install the backup again. ;)

**Comment by woltage** [comment]
Released.. couple of days ago ;)

**Comment by unexist** [comment]
Hm, I don't see any progress there, I still have the actionbar wasting screen space. Do you need any further information?

Motorola Xoom, HC 3.2

**Comment by woltage** [comment]
Try to look settings at hostlisting

**Comment by unexist** [comment]
Ah nice, sorry next time I'll read the changelog and thanks for adding that option. :)
